apiVersion: v1

kind: Service

metadata:

  name: jenkins-jnlp

  namespace: devsecops

spec:

  selector:

    app: jenkins-server

  type: ClusterIP

  ports:

  - port: 50000

    targetPort: 50000

  type: ClusterIP






